// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: doc/lexer.jflex

package com.mynor.golite.lexer;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import com.mynor.golite.parser.Terminal;

@SuppressWarnings("fallthrough")
public class LexerGLT implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\4\23\1\24"+
    "\1\23\1\25\3\23\1\26\1\27\1\30\1\31\1\32"+
    "\2\0\1\33\4\34\1\35\2\34\1\36\1\37\4\34"+
    "\1\40\1\41\3\34\1\42\6\34\1\43\1\44\1\45"+
    "\1\0\1\34\1\0\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\34\1\57\1\60\1\61"+
    "\1\62\1\63\1\64\1\34\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\73\1\74\1\34\1\75\1\76\1\77"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\6\23\1\24\1\25"+
    "\16\23\1\26\1\1\1\27\1\30\1\31\1\0\1\32"+
    "\1\1\1\0\1\33\1\34\1\0\1\2\1\0\1\35"+
    "\1\36\1\37\1\40\22\23\1\41\13\23\1\42\1\1"+
    "\1\43\2\0\1\44\17\23\1\45\1\46\1\23\1\47"+
    "\1\50\1\23\1\51\7\23\1\52\1\2\1\53\1\23"+
    "\1\54\4\23\1\55\1\23\1\56\2\23\1\57\2\23"+
    "\1\60\1\61\10\23\1\62\1\63\4\23\1\64\2\23"+
    "\1\65\1\23\1\66\11\23\1\67\1\70\4\23\1\71"+
    "\1\72\1\23\1\73\1\74\1\75\1\23\1\76\1\23"+
    "\1\77\1\100\1\101\1\102\1\103\1\23\1\104\1\23"+
    "\1\105";

  private static int [] zzUnpackAction() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\100\0\u0140\0\u0180"+
    "\0\100\0\100\0\100\0\u01c0\0\100\0\u0200\0\100\0\u0240"+
    "\0\u0280\0\u02c0\0\100\0\u0300\0\u0340\0\u0380\0\u03c0\0\u0400"+
    "\0\u0440\0\u0480\0\u04c0\0\u0500\0\100\0\100\0\u0540\0\u0580"+
    "\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700\0\u0740\0\u0780"+
    "\0\u07c0\0\u0800\0\u0840\0\u0880\0\100\0\u08c0\0\100\0\100"+
    "\0\100\0\u0900\0\100\0\u0940\0\u0980\0\100\0\100\0\u09c0"+
    "\0\u0a00\0\u0a40\0\100\0\100\0\100\0\100\0\u0a80\0\u0ac0"+
    "\0\u0b00\0\u0b40\0\u0b80\0\u0bc0\0\u0c00\0\u0c40\0\u0c80\0\u0cc0"+
    "\0\u0d00\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0"+
    "\0\u0400\0\u0f00\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u1040\0\u1080"+
    "\0\u10c0\0\u1100\0\u1140\0\u1180\0\100\0\u11c0\0\100\0\u1200"+
    "\0\u1240\0\u0a40\0\u1280\0\u12c0\0\u1300\0\u1340\0\u1380\0\u13c0"+
    "\0\u1400\0\u1440\0\u1480\0\u14c0\0\u1500\0\u1540\0\u1580\0\u15c0"+
    "\0\u1600\0\u0400\0\u0400\0\u1640\0\u0400\0\u0400\0\u1680\0\u0400"+
    "\0\u16c0\0\u1700\0\u1740\0\u1780\0\u17c0\0\u1800\0\u1840\0\u0400"+
    "\0\u09c0\0\u0400\0\u1880\0\u0400\0\u18c0\0\u1900\0\u1940\0\u1980"+
    "\0\u0400\0\u19c0\0\u0400\0\u1a00\0\u1a40\0\u0400\0\u1a80\0\u1ac0"+
    "\0\u0400\0\u0400\0\u1b00\0\u1b40\0\u1b80\0\u1bc0\0\u1c00\0\u1c40"+
    "\0\u1c80\0\u1cc0\0\u0400\0\u0400\0\u1d00\0\u1d40\0\u1d80\0\u1dc0"+
    "\0\u0400\0\u1e00\0\u1e40\0\u0400\0\u1e80\0\u0400\0\u1ec0\0\u1f00"+
    "\0\u1f40\0\u1f80\0\u1fc0\0\u2000\0\u2040\0\u2080\0\u20c0\0\u0400"+
    "\0\u0400\0\u2100\0\u2140\0\u2180\0\u21c0\0\u0400\0\u0400\0\u2200"+
    "\0\u2240\0\u0400\0\u0400\0\u2280\0\u0400\0\u22c0\0\u0400\0\u0400"+
    "\0\u0400\0\u0400\0\u0400\0\u2300\0\u0400\0\u2340\0\u0400";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\3\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\2\30\1\31\1\32\1\30\1\33\1\34\1\35\1\2"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\2\30"+
    "\1\45\1\30\1\46\1\47\1\50\2\30\1\51\1\52"+
    "\1\53\1\30\1\54\3\30\1\55\1\56\1\57\101\0"+
    "\2\3\1\0\2\3\123\0\1\60\46\0\2\5\1\0"+
    "\2\5\1\0\1\5\1\61\34\5\1\62\33\5\11\0"+
    "\1\63\66\0\2\64\1\0\2\64\1\0\4\64\1\0"+
    "\31\64\1\65\33\64\31\0\1\66\77\0\1\67\63\0"+
    "\1\70\4\0\1\71\76\0\1\72\1\0\3\21\103\0"+
    "\1\73\77\0\1\74\77\0\1\75\77\0\1\76\71\0"+
    "\3\30\5\0\10\30\3\0\21\30\1\77\5\30\26\0"+
    "\3\30\5\0\10\30\3\0\27\30\26\0\3\30\5\0"+
    "\10\30\3\0\14\30\1\100\12\30\26\0\3\30\5\0"+
    "\10\30\3\0\15\30\1\101\11\30\26\0\3\30\5\0"+
    "\10\30\3\0\1\102\16\30\1\103\7\30\26\0\3\30"+
    "\5\0\10\30\3\0\26\30\1\104\26\0\3\30\5\0"+
    "\10\30\3\0\16\30\1\105\10\30\26\0\3\30\5\0"+
    "\10\30\3\0\15\30\1\106\1\30\1\107\7\30\26\0"+
    "\3\30\5\0\10\30\3\0\1\110\14\30\1\111\11\30"+
    "\26\0\3\30\5\0\10\30\3\0\4\30\1\112\22\30"+
    "\26\0\3\30\5\0\10\30\3\0\12\30\1\113\14\30"+
    "\26\0\3\30\5\0\10\30\3\0\1\114\11\30\1\115"+
    "\1\116\1\30\1\117\4\30\1\120\4\30\26\0\3\30"+
    "\5\0\10\30\3\0\5\30\1\121\6\30\1\122\12\30"+
    "\26\0\3\30\5\0\10\30\3\0\4\30\1\123\22\30"+
    "\26\0\3\30\5\0\10\30\3\0\1\124\26\30\26\0"+
    "\3\30\5\0\10\30\3\0\10\30\1\125\16\30\26\0"+
    "\3\30\5\0\10\30\3\0\1\126\3\30\1\127\22\30"+
    "\26\0\3\30\5\0\10\30\3\0\12\30\1\130\6\30"+
    "\1\131\2\30\1\132\2\30\26\0\3\30\5\0\10\30"+
    "\3\0\17\30\1\133\7\30\26\0\3\30\5\0\10\30"+
    "\3\0\1\134\26\30\101\0\1\135\1\0\2\5\4\0"+
    "\72\5\2\136\1\0\2\136\1\0\4\136\1\137\31\136"+
    "\1\140\33\136\2\64\4\0\72\64\15\70\1\141\62\70"+
    "\2\71\1\0\75\71\23\0\3\142\75\0\3\30\5\0"+
    "\10\30\3\0\15\30\1\143\11\30\26\0\3\30\5\0"+
    "\10\30\3\0\3\30\1\144\23\30\26\0\3\30\5\0"+
    "\10\30\3\0\10\30\1\145\16\30\26\0\3\30\5\0"+
    "\10\30\3\0\17\30\1\146\7\30\26\0\3\30\5\0"+
    "\10\30\3\0\10\30\1\147\16\30\26\0\3\30\5\0"+
    "\10\30\3\0\16\30\1\150\10\30\26\0\3\30\5\0"+
    "\10\30\3\0\16\30\1\151\10\30\26\0\3\30\5\0"+
    "\10\30\3\0\15\30\1\152\11\30\26\0\3\30\5\0"+
    "\10\30\3\0\4\30\1\153\22\30\26\0\3\30\5\0"+
    "\10\30\3\0\20\30\1\154\6\30\26\0\3\30\5\0"+
    "\10\30\3\0\14\30\1\155\12\30\26\0\3\30\5\0"+
    "\10\30\3\0\5\30\1\156\21\30\26\0\3\30\5\0"+
    "\10\30\3\0\20\30\1\157\6\30\26\0\3\30\5\0"+
    "\10\30\3\0\12\30\1\160\14\30\26\0\3\30\5\0"+
    "\10\30\3\0\15\30\1\161\11\30\26\0\3\30\5\0"+
    "\10\30\3\0\21\30\1\162\5\30\26\0\3\30\5\0"+
    "\10\30\3\0\17\30\1\163\7\30\26\0\3\30\5\0"+
    "\10\30\3\0\14\30\1\164\12\30\26\0\3\30\5\0"+
    "\10\30\3\0\21\30\1\165\5\30\26\0\3\30\5\0"+
    "\10\30\3\0\14\30\1\166\12\30\26\0\3\30\5\0"+
    "\10\30\3\0\10\30\1\167\16\30\26\0\3\30\5\0"+
    "\10\30\3\0\12\30\1\170\14\30\26\0\3\30\5\0"+
    "\10\30\3\0\14\30\1\171\12\30\26\0\3\30\5\0"+
    "\10\30\3\0\5\30\1\172\13\30\1\173\5\30\26\0"+
    "\3\30\5\0\10\30\3\0\10\30\1\174\16\30\26\0"+
    "\3\30\5\0\10\30\3\0\17\30\1\175\7\30\26\0"+
    "\3\30\5\0\10\30\3\0\10\30\1\176\16\30\26\0"+
    "\3\30\5\0\10\30\3\0\22\30\1\177\4\30\26\0"+
    "\3\30\5\0\10\30\3\0\17\30\1\200\7\30\3\0"+
    "\2\136\1\0\2\136\1\0\4\136\1\0\31\136\1\140"+
    "\35\136\4\0\72\136\15\70\1\141\4\70\1\201\55\70"+
    "\23\0\3\30\5\0\10\30\3\0\10\30\1\202\16\30"+
    "\26\0\3\30\5\0\10\30\3\0\4\30\1\203\22\30"+
    "\26\0\3\30\5\0\10\30\3\0\14\30\1\204\12\30"+
    "\26\0\3\30\5\0\10\30\3\0\20\30\1\205\6\30"+
    "\26\0\3\30\5\0\10\30\3\0\14\30\1\206\12\30"+
    "\26\0\3\30\5\0\10\30\3\0\4\30\1\207\22\30"+
    "\26\0\3\30\5\0\10\30\3\0\4\30\1\210\22\30"+
    "\26\0\3\30\5\0\10\30\3\0\12\30\1\211\14\30"+
    "\26\0\3\30\5\0\10\30\3\0\1\212\26\30\26\0"+
    "\3\30\5\0\10\30\3\0\4\30\1\213\22\30\26\0"+
    "\3\30\5\0\10\30\3\0\21\30\1\214\5\30\26\0"+
    "\3\30\5\0\10\30\3\0\1\215\26\30\26\0\3\30"+
    "\5\0\10\30\3\0\4\30\1\216\22\30\26\0\3\30"+
    "\5\0\10\30\3\0\20\30\1\217\6\30\26\0\3\30"+
    "\5\0\10\30\3\0\1\220\26\30\26\0\3\30\5\0"+
    "\10\30\3\0\2\30\1\221\24\30\26\0\3\30\5\0"+
    "\10\30\3\0\14\30\1\222\12\30\26\0\3\30\5\0"+
    "\10\30\3\0\6\30\1\223\20\30\26\0\3\30\5\0"+
    "\10\30\3\0\12\30\1\224\14\30\26\0\3\30\5\0"+
    "\10\30\3\0\22\30\1\225\4\30\26\0\3\30\5\0"+
    "\10\30\3\0\2\30\1\226\24\30\26\0\3\30\5\0"+
    "\10\30\3\0\2\30\1\227\5\30\1\230\11\30\1\231"+
    "\4\30\26\0\3\30\5\0\10\30\3\0\21\30\1\232"+
    "\5\30\26\0\3\30\5\0\10\30\3\0\4\30\1\233"+
    "\22\30\26\0\3\30\5\0\10\30\3\0\25\30\1\234"+
    "\1\30\26\0\3\30\5\0\10\30\3\0\4\30\1\235"+
    "\22\30\26\0\3\30\5\0\10\30\3\0\21\30\1\236"+
    "\5\30\26\0\3\30\5\0\5\30\1\237\2\30\3\0"+
    "\27\30\26\0\3\30\5\0\10\30\3\0\14\30\1\240"+
    "\12\30\26\0\3\30\5\0\10\30\3\0\11\30\1\241"+
    "\15\30\26\0\3\30\5\0\10\30\3\0\10\30\1\242"+
    "\16\30\26\0\3\30\5\0\10\30\3\0\22\30\1\243"+
    "\4\30\26\0\3\30\5\0\10\30\3\0\4\30\1\244"+
    "\22\30\26\0\3\30\5\0\10\30\3\0\21\30\1\245"+
    "\5\30\26\0\3\30\5\0\10\30\3\0\4\30\1\246"+
    "\22\30\26\0\3\30\5\0\10\30\3\0\4\30\1\247"+
    "\22\30\26\0\3\30\5\0\10\30\3\0\17\30\1\250"+
    "\7\30\26\0\3\30\5\0\10\30\3\0\4\30\1\251"+
    "\22\30\26\0\3\30\5\0\10\30\3\0\15\30\1\252"+
    "\11\30\26\0\3\30\5\0\10\30\3\0\14\30\1\253"+
    "\12\30\26\0\3\30\5\0\10\30\3\0\2\30\1\254"+
    "\24\30\26\0\3\30\5\0\10\30\3\0\2\30\1\255"+
    "\24\30\26\0\3\30\5\0\2\30\1\256\5\30\3\0"+
    "\27\30\26\0\3\30\5\0\10\30\3\0\12\30\1\257"+
    "\14\30\26\0\3\30\5\0\10\30\3\0\5\30\1\260"+
    "\21\30\26\0\3\30\5\0\10\30\3\0\3\30\1\261"+
    "\23\30\26\0\3\30\5\0\10\30\3\0\14\30\1\262"+
    "\12\30\26\0\3\30\5\0\10\30\3\0\12\30\1\263"+
    "\14\30\26\0\2\30\1\264\5\0\10\30\3\0\27\30"+
    "\26\0\3\30\5\0\10\30\3\0\2\30\1\265\24\30"+
    "\26\0\3\30\5\0\10\30\3\0\14\30\1\266\12\30"+
    "\26\0\3\30\5\0\10\30\3\0\20\30\1\267\6\30"+
    "\26\0\3\30\5\0\10\30\3\0\14\30\1\270\12\30"+
    "\26\0\3\30\5\0\10\30\3\0\6\30\1\271\20\30"+
    "\26\0\3\30\5\0\10\30\3\0\21\30\1\272\5\30"+
    "\26\0\3\30\5\0\10\30\3\0\7\30\1\273\17\30"+
    "\26\0\3\30\5\0\10\30\3\0\12\30\1\274\14\30"+
    "\26\0\3\30\5\0\10\30\3\0\14\30\1\275\12\30"+
    "\26\0\3\30\5\0\10\30\3\0\22\30\1\276\4\30"+
    "\26\0\3\30\5\0\10\30\3\0\21\30\1\277\5\30"+
    "\26\0\1\30\1\300\1\30\5\0\10\30\3\0\27\30"+
    "\26\0\3\30\5\0\10\30\3\0\21\30\1\301\5\30"+
    "\26\0\3\30\5\0\10\30\3\0\23\30\1\302\3\30"+
    "\26\0\3\30\5\0\10\30\3\0\20\30\1\303\6\30"+
    "\26\0\3\30\5\0\10\30\3\0\15\30\1\304\11\30"+
    "\26\0\3\30\5\0\10\30\3\0\4\30\1\305\22\30"+
    "\26\0\3\30\5\0\10\30\3\0\1\306\26\30\26\0"+
    "\3\30\5\0\10\30\3\0\21\30\1\307\5\30\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9088];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\1\11\3\1\1\11\11\1\2\11\16\1\1\11"+
    "\1\1\3\11\1\0\1\11\1\1\1\0\2\11\1\0"+
    "\1\1\1\0\4\11\36\1\1\11\1\1\1\11\2\0"+
    "\146\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    ArrayList<Token> tokens = new ArrayList<>();

    public void addToken(int linea, int columna, String lexema, TipoToken tipo) {
        tokens.add(new Token(linea, columna, lexema, tipo));
    }

    public ArrayList<Token> getTokens() {
        return tokens;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerGLT(java.io.Reader in) {
      yyline   = 0;
    yycolumn = 0;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new Symbol(Terminal.EOF, yyline, yycolumn);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.ERROR);
            }
          // fall through
          case 70: break;
          case 2:
            { 
            }
          // fall through
          case 71: break;
          case 3:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.NOT); return new Symbol(Terminal.NOT,        yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 4:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MODULO); return new Symbol(Terminal.MODULO,     yyline, yycolumn);
            }
          // fall through
          case 73: break;
          case 5:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.PAR_IZQ); return new Symbol(Terminal.PAR_IZQ,    yyline, yycolumn);
            }
          // fall through
          case 74: break;
          case 6:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.PAR_DER); return new Symbol(Terminal.PAR_DER,    yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 7:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MULT); return new Symbol(Terminal.MULT,       yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 8:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MAS); return new Symbol(Terminal.MAS,        yyline, yycolumn);
            }
          // fall through
          case 77: break;
          case 9:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.COMA); return new Symbol(Terminal.COMA,       yyline, yycolumn);
            }
          // fall through
          case 78: break;
          case 10:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MENOS); return new Symbol(Terminal.MENOS,      yyline, yycolumn);
            }
          // fall through
          case 79: break;
          case 11:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.PUNTO); return new Symbol(Terminal.PUNTO,      yyline, yycolumn);
            }
          // fall through
          case 80: break;
          case 12:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.DIV); return new Symbol(Terminal.DIV,        yyline, yycolumn);
            }
          // fall through
          case 81: break;
          case 13:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.ENTERO); return new Symbol(Terminal.ENTERO,       yyline, yycolumn, Integer.parseInt(yytext()));
            }
          // fall through
          case 82: break;
          case 14:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.DOS_PUNTOS); return new Symbol(Terminal.DOS_PUNTOS, yyline, yycolumn);
            }
          // fall through
          case 83: break;
          case 15:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.PUNTO_COMA); return new Symbol(Terminal.PUNTO_COMA, yyline, yycolumn);
            }
          // fall through
          case 84: break;
          case 16:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MENOR); return new Symbol(Terminal.MENOR,      yyline, yycolumn);
            }
          // fall through
          case 85: break;
          case 17:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.ASIG); return new Symbol(Terminal.ASIG,       yyline, yycolumn);
            }
          // fall through
          case 86: break;
          case 18:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MAYOR); return new Symbol(Terminal.MAYOR,      yyline, yycolumn);
            }
          // fall through
          case 87: break;
          case 19:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.IDENTIFICADOR); return new Symbol(Terminal.IDENTIFICADOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 20:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.COR_IZQ); return new Symbol(Terminal.COR_IZQ,    yyline, yycolumn);
            }
          // fall through
          case 89: break;
          case 21:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.COR_DER); return new Symbol(Terminal.COR_DER,    yyline, yycolumn);
            }
          // fall through
          case 90: break;
          case 22:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.LLA_IZQ); return new Symbol(Terminal.LLA_IZQ,    yyline, yycolumn);
            }
          // fall through
          case 91: break;
          case 23:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.LLA_DER); return new Symbol(Terminal.LLA_DER,    yyline, yycolumn);
            }
          // fall through
          case 92: break;
          case 24:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.NO_IGUAL); return new Symbol(Terminal.NO_IGUAL,    yyline, yycolumn);
            }
          // fall through
          case 93: break;
          case 25:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.CADENA); return new Symbol(Terminal.CADENA, yyline, yycolumn, yytext().substring(1, yytext().length() - 1));
            }
          // fall through
          case 94: break;
          case 26:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.AND); return new Symbol(Terminal.AND,         yyline, yycolumn);
            }
          // fall through
          case 95: break;
          case 27:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.PLUS_ASIG); return new Symbol(Terminal.PLUS_ASIG,   yyline, yycolumn);
            }
          // fall through
          case 96: break;
          case 28:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MINUS_ASIG); return new Symbol(Terminal.MINUS_ASIG,  yyline, yycolumn);
            }
          // fall through
          case 97: break;
          case 29:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.DECL_ASIG); return new Symbol(Terminal.DECL_ASIG,   yyline, yycolumn);
            }
          // fall through
          case 98: break;
          case 30:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MENOR_IGUAL); return new Symbol(Terminal.MENOR_IGUAL, yyline, yycolumn);
            }
          // fall through
          case 99: break;
          case 31:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.IGUAL); return new Symbol(Terminal.IGUAL,       yyline, yycolumn);
            }
          // fall through
          case 100: break;
          case 32:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MAYOR_IGUAL); return new Symbol(Terminal.MAYOR_IGUAL, yyline, yycolumn);
            }
          // fall through
          case 101: break;
          case 33:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.IF); return new Symbol(Terminal.IF,       yyline, yycolumn);
            }
          // fall through
          case 102: break;
          case 34:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.OR); return new Symbol(Terminal.OR,          yyline, yycolumn);
            }
          // fall through
          case 103: break;
          case 35:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.RUNE_LIT); return new Symbol(Terminal.RUNE_LIT, yyline, yycolumn, yytext().charAt(1));
            }
          // fall through
          case 104: break;
          case 36:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.FLOTANTE); return new Symbol(Terminal.FLOTANTE,     yyline, yycolumn, Double.parseDouble(yytext()));
            }
          // fall through
          case 105: break;
          case 37:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.FMT); return new Symbol(Terminal.FMT,        yyline, yycolumn);
            }
          // fall through
          case 106: break;
          case 38:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.FOR); return new Symbol(Terminal.FOR,      yyline, yycolumn);
            }
          // fall through
          case 107: break;
          case 39:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.INT); return new Symbol(Terminal.INT,      yyline, yycolumn);
            }
          // fall through
          case 108: break;
          case 40:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.LEN); return new Symbol(Terminal.LEN,      yyline, yycolumn);
            }
          // fall through
          case 109: break;
          case 41:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.NIL); return new Symbol(Terminal.NIL,      yyline, yycolumn);
            }
          // fall through
          case 110: break;
          case 42:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.VAR); return new Symbol(Terminal.VAR,      yyline, yycolumn);
            }
          // fall through
          case 111: break;
          case 43:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.ATOI); return new Symbol(Terminal.ATOI,       yyline, yycolumn);
            }
          // fall through
          case 112: break;
          case 44:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.JOIN); return new Symbol(Terminal.JOIN,       yyline, yycolumn);
            }
          // fall through
          case 113: break;
          case 45:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.BOOL); return new Symbol(Terminal.BOOL,     yyline, yycolumn);
            }
          // fall through
          case 114: break;
          case 46:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.CASE); return new Symbol(Terminal.CASE,     yyline, yycolumn);
            }
          // fall through
          case 115: break;
          case 47:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.ELSE); return new Symbol(Terminal.ELSE,     yyline, yycolumn);
            }
          // fall through
          case 116: break;
          case 48:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.FUNC); return new Symbol(Terminal.FUNC,     yyline, yycolumn);
            }
          // fall through
          case 117: break;
          case 49:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.MAIN); return new Symbol(Terminal.MAIN,     yyline, yycolumn);
            }
          // fall through
          case 118: break;
          case 50:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.TRUE); return new Symbol(Terminal.TRUE,     yyline, yycolumn);
            }
          // fall through
          case 119: break;
          case 51:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.INDEX); return new Symbol(Terminal.INDEX,      yyline, yycolumn);
            }
          // fall through
          case 120: break;
          case 52:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.BREAK); return new Symbol(Terminal.BREAK,    yyline, yycolumn);
            }
          // fall through
          case 121: break;
          case 53:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.FALSE); return new Symbol(Terminal.FALSE,    yyline, yycolumn);
            }
          // fall through
          case 122: break;
          case 54:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.RANGE); return new Symbol(Terminal.RANGE,    yyline, yycolumn);
            }
          // fall through
          case 123: break;
          case 55:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.TYPEOF); return new Symbol(Terminal.TYPEOF,     yyline, yycolumn);
            }
          // fall through
          case 124: break;
          case 56:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.APPEND); return new Symbol(Terminal.APPEND,   yyline, yycolumn);
            }
          // fall through
          case 125: break;
          case 57:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.RETURN); return new Symbol(Terminal.RETURN,   yyline, yycolumn);
            }
          // fall through
          case 126: break;
          case 58:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.SLICES); return new Symbol(Terminal.SLICES,     yyline, yycolumn);
            }
          // fall through
          case 127: break;
          case 59:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.STRING); return new Symbol(Terminal.STRING,   yyline, yycolumn);
            }
          // fall through
          case 128: break;
          case 60:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.STRUCT); return new Symbol(Terminal.STRUCT,   yyline, yycolumn);
            }
          // fall through
          case 129: break;
          case 61:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.SWITCH); return new Symbol(Terminal.SWITCH,   yyline, yycolumn);
            }
          // fall through
          case 130: break;
          case 62:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.PRINTLN); return new Symbol(Terminal.PRINTLN,    yyline, yycolumn);
            }
          // fall through
          case 131: break;
          case 63:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.DEFAULT); return new Symbol(Terminal.DEFAULT,  yyline, yycolumn);
            }
          // fall through
          case 132: break;
          case 64:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.FLOAT64); return new Symbol(Terminal.FLOAT64,  yyline, yycolumn);
            }
          // fall through
          case 133: break;
          case 65:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.REFLECT); return new Symbol(Terminal.REFLECT,    yyline, yycolumn);
            }
          // fall through
          case 134: break;
          case 66:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.STRCONV); return new Symbol(Terminal.STRCONV,    yyline, yycolumn);
            }
          // fall through
          case 135: break;
          case 67:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.STRINGS); return new Symbol(Terminal.STRINGS,    yyline, yycolumn);
            }
          // fall through
          case 136: break;
          case 68:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.CONTINUE); return new Symbol(Terminal.CONTINUE, yyline, yycolumn);
            }
          // fall through
          case 137: break;
          case 69:
            { addToken(yyline + 1, yycolumn + 1, yytext(), TipoToken.PARSEFLOAT); return new Symbol(Terminal.PARSEFLOAT, yyline, yycolumn);
            }
          // fall through
          case 138: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
