
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mynor.golite.parser;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import com.mynor.golite.lexer.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserGLT extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Terminal.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserGLT() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserGLT(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserGLT(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\004\000\002\002\004\000\002\003" +
    "\005\000\002\004\002\000\002\004\006\000\002\005\002" +
    "\000\002\005\004\000\002\006\010\000\002\006\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\025\000\004\004\005\001\002\000\004\002\027\001" +
    "\002\000\004\041\025\001\002\000\010\002\ufffc\006\ufffc" +
    "\010\ufffc\001\002\000\010\002\000\006\011\010\010\001" +
    "\002\000\004\041\020\001\002\000\004\007\013\001\002" +
    "\000\010\002\ufffb\006\ufffb\010\ufffb\001\002\000\004\065" +
    "\014\001\002\000\004\066\015\001\002\000\004\071\016" +
    "\001\002\000\004\072\017\001\002\000\010\002\ufff9\006" +
    "\ufff9\010\ufff9\001\002\000\004\026\021\001\002\000\004" +
    "\061\022\001\002\000\004\036\023\001\002\000\004\074" +
    "\024\001\002\000\010\002\ufffa\006\ufffa\010\ufffa\001\002" +
    "\000\004\074\026\001\002\000\010\002\uffff\006\uffff\010" +
    "\uffff\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\025\000\006\002\003\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\006\001\001\000\004" +
    "\006\011\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserGLT$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserGLT$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserGLT$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

    return getScanner().next_token();

    }


    private final List<String> erroresSintacticos = new ArrayList<>();
    public Symbol ultimoError = null;

    public List<String> getErroresSintacticos(){
        return erroresSintacticos;
    }

    private int linea(Symbol s) {
        return s == null ? -1 : s.left;
    }

    private int columna(Symbol s) {
        return s == null ? -1 : s.right;
    }

    private String ubicacion(Symbol s) {
        if (s == null) return "fin de entrada";
        return "línea " + linea(s) + ", columna " + columna(s);
    }

    @Override
    public void report_error(String message, Object info) {
        if (info instanceof Symbol s) {
            ultimoError = s;
            erroresSintacticos.add(
                "Error sintáctico en " + ubicacion(s) + ": " + message
            );
        } else {
            erroresSintacticos.add("Error sintáctico: " + message);
        }
    }

    @Override
    public void syntax_error(Symbol cur_token) {
        ultimoError = cur_token;
        if (cur_token != null) {
            erroresSintacticos.add(
                "Token inesperado en " + ubicacion(cur_token)
            );
        } else {
            erroresSintacticos.add("Error sintáctico: fin de entrada inesperado");
        }
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token) throws Exception {
        ultimoError = cur_token;
        if (cur_token != null) {
            erroresSintacticos.add(
                "No se pudo recuperar del error en " + ubicacion(cur_token)
            );
        } else {
            erroresSintacticos.add(
                "No se pudo recuperar del error al final de la entrada"
            );
        }
        throw new Exception("Error sintáctico: " + (ultimoError.left) + ":" + (ultimoError.right));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserGLT$actions {
  private final ParserGLT parser;

  /** Constructor */
  CUP$ParserGLT$actions(ParserGLT parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserGLT$do_action_part00000000(
    int                        CUP$ParserGLT$act_num,
    java_cup.runtime.lr_parser CUP$ParserGLT$parser,
    java.util.Stack            CUP$ParserGLT$stack,
    int                        CUP$ParserGLT$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserGLT$result;

      /* select the action based on the action number */
      switch (CUP$ParserGLT$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)).value;
		RESULT = start_val;
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)), ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserGLT$parser.done_parsing();
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= paquete declaraciones 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)), ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // paquete ::= PACKAGE IDENTIFICADOR PUNTO_COMA 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("paquete",1, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_imports ::= 
            {
              Object RESULT =null;
		 RESULT = new ArrayList<>(); 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("lista_imports",2, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_imports ::= lista_imports IMPORT CADENA PUNTO_COMA 
            {
              Object RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-3)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-3)).right;
		Object li = (Object)((java_cup.runtime.Symbol) CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-3)).value;
		 RESULT = li; 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("lista_imports",2, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-3)), ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaraciones ::= 
            {
              Object RESULT =null;
		 RESULT = new ArrayList<>(); 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("declaraciones",3, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaraciones ::= declaraciones declaracion 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)).value;
		int declleft = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()).left;
		int declright = ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()).right;
		Object decl = (Object)((java_cup.runtime.Symbol) CUP$ParserGLT$stack.peek()).value;
		 RESULT = d; 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("declaraciones",3, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-1)), ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracion ::= VAR IDENTIFICADOR INT ASIG ENTERO PUNTO_COMA 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-5)), ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracion ::= FUNC MAIN PAR_IZQ PAR_DER LLA_IZQ LLA_DER 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$ParserGLT$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.elementAt(CUP$ParserGLT$top-5)), ((java_cup.runtime.Symbol)CUP$ParserGLT$stack.peek()), RESULT);
            }
          return CUP$ParserGLT$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserGLT$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserGLT$do_action(
    int                        CUP$ParserGLT$act_num,
    java_cup.runtime.lr_parser CUP$ParserGLT$parser,
    java.util.Stack            CUP$ParserGLT$stack,
    int                        CUP$ParserGLT$top)
    throws java.lang.Exception
    {
              return CUP$ParserGLT$do_action_part00000000(
                               CUP$ParserGLT$act_num,
                               CUP$ParserGLT$parser,
                               CUP$ParserGLT$stack,
                               CUP$ParserGLT$top);
    }
}

}
